apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: go-api-starter
  labels:
    app.kubernetes.io/name: go-api-starter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-api-starter
