apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-api-starter
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.yourdomain.com
      secretName: go-api-starter-tls-prod
  rules:
    - host: api.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-api-starter
                port:
                  name: http
